export type UserResponseAPI = {
  login: string,
  id: number,
  node_id: string,
  avatar_url: URL,
  gravatar_id: string,
  url: URL,
  html_url: URL,
  followers_url: URL,
  following_url: URL,
  gists_url: URL,
  starred_url: URL,
  subscriptions_url: URL,
  organizations_url: URL,
  repos_url: URL,
  events_url: URL,
  received_events_url: URL,
  type: string,
  site_admin: boolean,
  name: string,
  company: string,
  blog: URL,
  location: string,
  email: null | string,
  hireable: null | string,
  bio: null | string,
  twitter_username: null | string,
  public_repos: number,
  public_gists: number,
  followers: number,
  following: number,
  created_at: Date,
  updated_at: Date,
}

export type ResponseAPI<R, E> = { result: 'success', data: R } | { result: 'error', error: E }